### ISSUE TITLE
Encapsulate getting data into a module

### ISSUE THREAD

**Issue by vidia** [Purdue-ACM-SIGAPP/PurdueLaundry-server#23]
Right now, we have the code for grabbing machines from redis and the code for getting it from washalert in the same module, heck, the same _function_. It would be better to have that put into a new module with functions such as:

getMachinesForLocation(location, callback)
getMachinesForAllLocations(callback)

Then have the impl attempt to get the data from redis FIRST, and when redis is not available, fall back to getting it from WashAlert directly.

**Comment by piticent123** [comment]
This already fixed in the `testing` branch. I will report back later
